

name: Deploy Portfolio

on: 
  push:
    branches:
      - main

jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      # Uncomment these steps if you need Node.js and to build your project
      # - name: Install Node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 16

      # - name: Install Dependencies
      #   run: npm ci

      # - name: Run Build
      #   run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.S3ACCESSKEY }}
          aws-secret-access-key: ${{ secrets.S3SECRETKEY }}
          aws-region: us-east-1
          
      - name: Deploy To S3 Bucket
        run: aws s3 sync . s3://raghav-dav

        
     
